spring:
  application:
    name: reg-service
eureka:
  instance:
    hostname: reg-serv.herokuapp.com
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
server:
  port: ${PORT:8080}
